# Generated by Django 6.0.6 on 2026-07-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passports', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportapplication',
            name='application_type',
            field=models.CharField(choices=[('new', 'New'), ('renewal', 'Renewal'), ('correction', 'Correction'), ('reissue', 'Reissue (Lost/Damaged)')], default='new', max_length=20),
        ),
    ]
